server:
  port: 8084
#DEFINICION DE LOS TOPICOS DE KAFKA
kafka:
  subscribed-topic:
    name: transaction-request
  topic-to-publish:
    name: transaction-response


spring:
#=====CONFIGURACION DE KAFKA=====
  kafka:
#Definimos los clusters donde van a estar los tópicos
    bootstrap-server: localhost:9092
#Group Id para nuestro tópico
    consumer:
      group-id: transaction-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

bootcoins-api:
  base-url: http://localhost:8080